name: Release Project

on:
  release:
    types: [ released ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Extract tag name
        id: extract_tagname
        shell: bash
        # Extra the tagname form the git reference, value of GITHUB_REF will be something like refs/tags/<tag_name>.
        run: echo "##[set-output name=tagname;]$(echo ${GITHUB_REF##*/})"
      - name: Set up JDK 1.11
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Set version with Maven
        run: ./mvnw -B versions:set -DprocessAllModules=true -DnewVersion=${{ steps.extract_tagname.outputs.tagname }}
      - name: Deploy with Maven to GitHub Packages
        run: ./mvnw -B -Prelease clean deploy