name: Release Project

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Extract tag name
        id: extract_tagname
        shell: bash
        # Extra the tagname form the git reference, value of GITHUB_REF will be something like refs/tags/<tag_name>.
        run: echo "##[set-output name=tagname;]$(echo ${GITHUB_REF##*/})"
      - name: Set version with Maven
        run: mvn -B versions:set -DprocessAllModules=true -DnewVersion=${{ steps.extract_tagname.outputs.tagname }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish package
        id: publish_package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Microsoft Teams Notification
        uses: Skitionek/notify-microsoft-teams@v1.0.4
        if: always()
        with:
          webhook_url: https://romdhani.webhook.office.com/webhookb2/285a147d-7095-4590-bfe5-d74ef8cc8943@76ea0493-2f30-4c80-8ac2-28ef7f601251/IncomingWebhook/b777cfe06b6241e1a4f70426ca56ebf8/7cada548-c235-478f-a4f9-3d16dd98cb1f
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          steps: ${{ toJson(steps) }}
          overwrite: "{title: `${steps.publish_package.outcome}`}"
          dry_run: false